apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.example.com
spec:
  group: example.com
  names:
    kind: HelloWorld
    listKind: HelloWorldList
    plural: helloworlds
    singular: helloworld
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            status:
              description: HelloWorldStatus defines the observed state of HelloWorld.
              type: object
              properties:
                conditions:
                  description: Conditions represent the latest available observations of an object's state.
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys:
                    - type
                  items:
                    description: Condition contains details for one aspect of the current state of this API Resource.
                    type: object
                    required:
                      - type
                      - status
                      - lastTransitionTime
                      - reason
                      - message
                    properties:
                      type:
                        description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        type: string
                        maxLength: 316
                        pattern: ^[A-Za-z0-9]([A-Za-z0-9_.-]*[A-Za-z0-9])?$
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      observedGeneration:
                        description: observedGeneration represents the .metadata.generation that the condition was set based upon.
                        type: integer
                        format: int64
                        minimum: 0
                      lastTransitionTime:
                        description: lastTransitionTime is the last time the condition transitioned from one status to another.
                        type: string
                        format: date-time
                      reason:
                        description: reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        type: string
                        minLength: 1
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      message:
                        description: message is a human readable message indicating details about the transition.
                        type: string
                        maxLength: 32768
    - name: v2
      served: true
      storage: false
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            status:
              description: HelloWorldStatus defines the observed state of HelloWorld.
              type: object
              properties:
                conditions:
                  description: Conditions represent the latest available observations of an object's state.
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys:
                    - type
                  items:
                    description: Condition contains details for one aspect of the current state of this API Resource.
                    type: object
                    required:
                      - type
                      - status
                      - lastTransitionTime
                      - reason
                      - message
                    properties:
                      type:
                        description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        type: string
                        maxLength: 316
                        pattern: ^[A-Za-z0-9]([A-Za-z0-9_.-]*[A-Za-z0-9])?$
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      observedGeneration:
                        description: observedGeneration represents the .metadata.generation that the condition was set based upon.
                        type: integer
                        format: int64
                        minimum: 0
                      lastTransitionTime:
                        description: lastTransitionTime is the last time the condition transitioned from one status to another.
                        type: string
                        format: date-time
                      reason:
                        description: reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        type: string
                        minLength: 1
                        maxLength: 1024
                        pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      message:
                        description: message is a human readable message indicating details about the transition.
                        type: string
                        maxLength: 32768
